version: '2'

services:
  mysql:
    restart: always
    image: mysql:5.7
    expose:
      - "3306"
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/docker-entrypoint-initdb.d
      - mysql:/var/lib/mysql
    env_file:
        - variables.env

  memcached:
    restart: always
    image: memcached:1.4-alpine
    ports:
      - "11211:11211"

  redis:
    restart: always
    image: redis:3.2-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis:/data

  app:
    build: docker/app
    restart: always
    working_dir: /project
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./application:/project
      - ./cache:/project/cache
      - ./logs:/project/logs
      - ./conf/php/cli.ini:/etc/php/7.0/cli/conf.d/100-custom.ini
      - ./conf/php/fpm.ini:/etc/php/7.0/fpm/conf.d/100-custom.ini
    depends_on:
      - mysql
      - redis
      - memcached
    env_file:
      - variables.env

volumes:
  mysql:
    driver: local
  redis:
    driver: local
